language: go

go:
 - go1.2.2

before_script:
 - wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.6.zip
 - unzip -q google_appengine_1.9.6.zip

script:
 - google_appengine/appcfg.py -q --oauth2_refresh_token=$TOKEN update ./

notifications:
 hipchat:
  rooms:
   - secure: "LMOJ34p5+E9a5iGJWpJMF93gln0r0unIC8Erm762fqmk9aQmwoyzzuV+z9ovfdzK9DOPi8k3FRsW0ERxZxB+WMdX6x3UYHV0K/Vd1b33Xt6D11tJ+xr8erMNhHMdh3l2G4QB2EnHi0tflffbAjhBzVR4csO+whvqvtR68fDInpw="
  template:
   - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'

env:
 global:
  secure: "fE8tKlnPNnYrR7qfHaDxBwfcxxhB8rcoPoIzEZ1iR/KIHR0vmCqcGn8ouVB2nFHeirW6h7p2E89x/RyQkHHuKdnAvmLAzGrCGbhbcCut1kAhEnCUhH7Wzzq3r+p4/6afC7usJ0GavgeGRnfYAmxm0Oy6TZ3PyI9Vh+Ks1RA+CCE="

